language: node_js
node_js:
- 12
script:
- npm run build
addons:
  ssh_known_hosts: hanbot.elviswolcott.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_9b645a4101e5_key -iv $encrypted_9b645a4101e5_iv
  -in deploy_ssh_key.enc -out /tmp/deploy_ssh_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ssh_key
- ssh-add /tmp/deploy_ssh_key
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    repo: ariporad/hanbot
    branch: master
